# Generated by Django 4.0.5 on 2022-06-10 06:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Date')),
                ('slug', models.SlugField(unique=True)),
                ('day', models.IntegerField(default=0, verbose_name='Кибон')),
                ('night', models.IntegerField(default=0, verbose_name='Ночные')),
                ('overtime', models.IntegerField(default=0, verbose_name='Чаноб')),
                ('holiday_pay', models.IntegerField(default=0, verbose_name='Тыкын')),
                ('holiday_overtime_pay', models.IntegerField(default=0, verbose_name='Тыкын-чаноб')),
                ('parking_allowance', models.IntegerField(default=0, verbose_name='Парковка')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_days', to='hours.month', verbose_name='Month')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_days', to='hours.shift', verbose_name='Смена')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
