# Generated by Django 4.0.5 on 2022-06-09 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workdays',
            old_name='holyday_work',
            new_name='holiday_work',
        ),
        migrations.AlterField(
            model_name='workdays',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='기본금'),
        ),
    ]
