# Generated by Django 4.0.5 on 2022-06-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdays',
            name='day',
            field=models.FloatField(default=0, verbose_name='Кибон'),
        ),
        migrations.AlterField(
            model_name='workdays',
            name='holiday_overtime_pay',
            field=models.FloatField(default=0, verbose_name='Тыкын-чаноб'),
        ),
        migrations.AlterField(
            model_name='workdays',
            name='holiday_pay',
            field=models.FloatField(default=0, verbose_name='Тыкын'),
        ),
        migrations.AlterField(
            model_name='workdays',
            name='night',
            field=models.FloatField(default=0, verbose_name='Ночные'),
        ),
        migrations.AlterField(
            model_name='workdays',
            name='overtime',
            field=models.FloatField(default=0, verbose_name='Чаноб'),
        ),
        migrations.AlterField(
            model_name='workdays',
            name='parking_allowance',
            field=models.FloatField(default=0, verbose_name='Парковка'),
        ),
    ]
