# Generated by Django 4.0.5 on 2022-06-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0002_rename_holyday_work_workdays_holiday_work_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workdays',
            old_name='holiday_work',
            new_name='holiday_pay',
        ),
        migrations.AddField(
            model_name='workdays',
            name='holiday_overtime_pay',
            field=models.IntegerField(default=0, verbose_name='Тыкын-чаноб'),
        ),
    ]
