# Generated by Django 4.0.5 on 2022-06-12 01:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0002_alter_workdays_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdays',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='workdays',
            name='day',
            field=models.FloatField(default=0, verbose_name='Стандартный день'),
        ),
        migrations.AlterField(
            model_name='workdays',
            name='holiday_overtime_pay',
            field=models.FloatField(default=0, verbose_name='Сверхурочные в выходые'),
        ),
        migrations.AlterField(
            model_name='workdays',
            name='holiday_pay',
            field=models.FloatField(default=0, verbose_name='Работа в выходые'),
        ),
        migrations.AlterField(
            model_name='workdays',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_days', to='hours.month', verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='workdays',
            name='overtime',
            field=models.FloatField(default=0, verbose_name='Сверхурочные'),
        ),
    ]
