# Generated by Django 4.0.5 on 2022-06-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0003_rename_holiday_work_workdays_holiday_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdays',
            name='parking_allowance',
            field=models.IntegerField(default=0, verbose_name='Парковка'),
        ),
    ]
