# Generated by Django 4.0.4 on 2022-06-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0003_alter_workdays_date_alter_workdays_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_st', models.IntegerField(default=9160)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
