# Generated by Django 4.0.5 on 2022-06-15 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0004_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdays',
            name='rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_days', to='hours.rate', verbose_name='Ставка'),
        ),
    ]
