# Generated by Django 4.0.4 on 2022-06-15 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0006_alter_workdays_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='months', to='hours.rate', verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate_st',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workdays',
            name='rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_days', to='hours.rate', verbose_name='Ставка'),
        ),
    ]
