# Generated by Django 4.0.5 on 2022-06-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0007_month_rate_alter_rate_rate_st_alter_workdays_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate_st',
            field=models.FloatField(default=0),
        ),
    ]
